controllers/LoginController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use Yii;


class LoginController extends Controller{

	public function actions(){
		return [
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'maxLength' => 4,
				'minLength' => 4,
				'width' => 80,
				'height' => 40
			],
		];
	}

	public function actionIndex(){

		$model = new \app\models\Login();

		if(Yii::$app->request->isPost && $model->load(Yii::$app->request->post()) && $model->login()){
			return $this->redirect(['center']);
		}

		return $this->renderPartial('index' , ['model' => $model]);
	}


	public function actionCenter(){
		
  		//echo base64_encode('admin123');
		//echo 'Center';
		//echo Yii::$app->session->get('mrs_username');
		
		if(!($username =  Yii::$app->session->get('mrs_username')) && !($username = \app\models\Login::loginByCookie())){
			//echo time();exit;
			
			return $this->redirect(['index']);
		}

		//echo '欢迎 , ' . $username;
		//return Yii::$app->session->get('mrs_username');exit;
		//return $this->goHome();
	    return $this->redirect(['logbook/index']);

		//var_dump(Yii::$app->session->get('mrs_username'));

	}
}







?>

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        
        $model->data=time();
     
        if ($model->load(Yii::$app->request->post())) {
        	
        	$model->password=md5(md5(Yii::$app->request->post()['User']['password']));
        	//echo 'asd';exit;
        	if($model->save()){
        		
        		return $this->redirect(['view', 'id' => $model->id]);
        	}else{
        		return $this->render('create', [
        				'model' => $model,
        				]);
        	}
        	//var_dump(Yii::$app->request->post());exit;
           
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        //var_dump($id);exit;
        //var_dump($model->password);exit;
		$arr= \Yii::$app->db->createCommand("SELECT password FROM user where id=$id")->queryOne(); ;
		
        if ($model->load(Yii::$app->request->post())) {
        	//var_dump($arr['password']);
        	//echo '<br>';
        	//var_dump(Yii::$app->request->post()['User']['password']);exit;
        	if($arr['password'] == (Yii::$app->request->post()['User']['password'])){
        		$model->password = $arr['password'];
        		if($model->save()){
        			return $this->redirect(['view', 'id' => $model->id]);
        		}
        	}else{
        		$model->password=md5(md5(Yii::$app->request->post()['User']['password']));
        		if($model->save()){
        			return $this->redirect(['view', 'id' => $model->id]);
        		}
        	}
        	
        	
           
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => '后台管理',
        'brandUrl' => ['/logbook/index'],
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    //var_dump(Yii::$app->user->isGuest);exit;
  //var_dump(Yii::$app->session->get('mrs_username'));exit;
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => '首页', 'url' => ['/logbook/index']],
        	['label' => '用户管理', 'url' => ['/user/index']],
        	['label' => '我的日志', 'url' => ['/logbook/logbook']],
            //['label' => 'About', 'url' => ['/site/about']],
           // ['label' => 'Contact', 'url' => ['/site/contact']],
            //['label' => 'Author', 'url' => ['/author/index']],
            /* ['label' => '国家', 'url' => ['/country/index'],
				'items'=>[['label'=>'添加文章','url'=>['/country/create']
						  ],['label'=>'修改文章','url'=>['/country/create']
						  ],['label'=>'删除文章','url'=>['/country/create']
]]], */
           // ['label' => 'Library', 'url' => ['/library/index']],            
            Yii::$app->session->get('mrs_username') ?
                 [
			'label' => '退出 (' . Yii::$app->session->get('mrs_username') . ')',
			'url' => ['/login'],
			'linkOptions' => ['data-method' => 'post']
										]:
                ['label' => '登录', 'url' => ['/login/index']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
        		'homeLink'=>[
        				    'label'=>'首页', //修改默认的Home
        		    'url'=>['logbook/index'], //修改默认的Home指向的url地址
        		 ],
        		
        		
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; 公司内部后台管理 <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>